name: Push Changes to Main Repo

on:
  push:
    branches:
      - main

jobs:
  push-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"  # Start the SSH agent
        ssh-add ~/.ssh/id_rsa    # Add the SSH key

    - name: Clone the central repository
      run: |
        git clone git@github.com:ChocofraiseTeam/Mainapp.git
        cd Mainapp

    - name: Clone Backend repository into the Backend folder
      run: |
        mkdir -p Backend
        git clone git@github.com:ChocofraiseTeam/Backend.git Backend
        cd ..

    - name: Show Git Status for Debugging after pull
      run: |
        git status

    - name: Add and commit changes
      run: |
        git config --global user.email "thomas.juin@epitech.eu"
        git config --global user.name "Thomas Juin"
        git add Backend
        git status
        git commit -m "Test Mirror"

    - name: Push to central repository
      run: |
        git push git@github.com:ChocofraiseTeam/Mainapp.git main
