on: workflow_dispatch # Manual trigger

jobs:
  push-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Backend
      uses: actions/checkout@v4

    - name: Setup SSH for Mainapp
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Clone Mainapp
      run: |
        git clone git@github.com:ChocofraiseTeam/Mainapp.git Mainapp

    - name: Add Backend as a Remote and Fetch Changes
      working-directory: Mainapp
      run: |
        git remote add Backend git@github.com:ChocofraiseTeam/Backend.git
        git fetch Backend main

    - name: Merge Backend Changes into Mainapp
      working-directory: Mainapp
      run: |
        git merge --no-ff Backend/main -m "Merge changes from Backend to Mainapp"

    - name: Commit and Push Changes to Mainapp
      working-directory: Mainapp
      run: |
        git push origin main
