name: Mirror to Central Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  mirror_to_central:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "Thomas Juin"
          git config --global user.email "thomas.juin@epitech.eu"

      - name: Mirror changes to central repository
        env:
          TOKEN: ${{ secrets.MainRepoToken }}
        run: |
          # Clone the central repository
          git clone https://{{$TOKEN}}@github.com/ChocofraiseTeam/Mainapp.git
          cd Mainapp

          # Create or navigate to the folder for this repository
          mkdir -p Backend  # Change 'repo1' to match the repository name
          cd Backend

          # Pull the latest changes from the source repository
          git config pull.rebase false
          git pull https://{{$TOKEN}}@github.com/ChocofraiseTeam/Backend.git main --allow-unrelated-histories

          # Add, commit, and push changes to the central repository
          cd ..
          git add .
          git commit -m "Test Mirror"
          git push https://{{$TOKEN}}@github.com/ChocofraiseTeam/Mainapp.git main
