name: Push Changes to Main Repo

on:
  push:
    branches:
      - main

jobs:
  push-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone the central repository
      run: |
        git clone https://{{$secrets.MainRepoToken}}@github.com/ChocofraiseTeam/Mainapp.git
        cd Mainapp

    - name: Show Git Status for Debugging
      run: |
        git status

    - name: Create Backend folder and pull changes
      run: |
        mkdir -p Backend
        cd Backend
        git config pull.rebase false
        git pull https://{{$secrets.MainRepoToken}}@github.com/ChocofraiseTeam/Backend.git main --allow-unrelated-histories
        cd ../..

    - name: Show Git Status for Debugging after pull
      run: |
        git status

    - name: Add and commit changes
      run: |
        git config --global user.email "thomas.juin@epitech.eu"
        git config --global user.name "Thomas Juin"
        git add Mainapp
        git status  # Add git status here for visibility
        git commit -m "Test Mirror"

    - name: Push to central repository
      run: |
        git push
