name: Mirror to Main Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  mirror_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "Thomas Juin"
          git config --global user.email "thomas.juin@epitech.eu"

      - name: Push to main repo
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR }}
        run: |
          git remote set-url --push origin https://${{ secrets.MIRROR }}@github.com/ChocofraiseTeam/Mainapp.git
          git fetch -p origin
          git push --mirror