name: Push Changes to Main Repo

on:
  push:
    branches:
      - main

jobs:
  push-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"  # Start the SSH agent
        ssh-add ~/.ssh/id_rsa    # Add the SSH key

    - name: Push to central repository
      run: |
        git clone git@github.com:ChocofraiseTeam/Mainapp.git
        cd Mainapp

        mkdir -p Backend
        cd Backend
        git pull git@github.com:ChocofraiseTeam/Backend.git main --allow-unrelated-histories
        cd ..
        git config --global user.email "thomas.juin@epitech.eu"
        git config --global user.name "Thomas Juin"
        git add Backend
        git status
        git commit -m "Test Mirror"
        git push git@github.com:ChocofraiseTeam/Mainapp.git main
